version: "3.4"
services:
  web:
    image: pramis/tcmg_412_project_9
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
      image: redis:latest
      command: ["redis-server", "--bind", "redis", "--port", "6379"]
networks:
  webnet:
